<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="6" failed="0" ignored="0" total="6" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="5046" started-at="2020-10-29T13:08:27Z" finished-at="2020-10-29T13:08:32Z">
    <groups>
    </groups>
    <test name="TestCase04" duration-ms="13" started-at="2020-10-29T13:08:27Z" finished-at="2020-10-29T13:08:27Z">
      <class name="first.TestCase04_getReadArticleScore">
        <test-method status="SKIP" signature="login()[pri:0, instance:first.TestCase04_getReadArticleScore@52feb982]" name="login" duration-ms="0" started-at="2020-10-29T21:08:27Z" finished-at="2020-10-29T21:08:27Z">
          <exception class="io.appium.java_client.service.local.InvalidServerInstanceException">
            <message>
              <![CDATA[Invalid server instance exception has occured: The invalid appium node /Applications/Appium.app/Contents/Resources/app/node_modules/appium/build/lib/main.js has been defined]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.InvalidServerInstanceException: Invalid server instance exception has occured: The invalid appium node /Applications/Appium.app/Contents/Resources/app/node_modules/appium/build/lib/main.js has been definedat io.appium.java_client.service.local.AppiumServiceBuilder.validateNodeStructure(AppiumServiceBuilder.java:107)at io.appium.java_client.service.local.AppiumServiceBuilder.checkAppiumJS(AppiumServiceBuilder.java:290)at io.appium.java_client.service.local.AppiumServiceBuilder.createArgs(AppiumServiceBuilder.java:386)at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:299)at io.appium.java_client.service.local.AppiumDriverLocalService.buildService(AppiumDriverLocalService.java:74)at first.Basic.SetUp(Basic.java:34)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at first.Runtest.main(Runtest.java:16)Caused by: java.io.IOException: The node /Applications/Appium.app/Contents/Resources/app/node_modules/appium/build/lib/main.jsdoesn't existat io.appium.java_client.service.local.AppiumServiceBuilder.validateNodeStructure(AppiumServiceBuilder.java:109)... 23 more]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.InvalidServerInstanceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="SKIP" signature="enterMy()[pri:0, instance:first.TestCase04_getReadArticleScore@52feb982]" name="enterMy" duration-ms="0" started-at="2020-10-29T21:08:27Z" depends-on-methods="first.TestCase04_getReadArticleScore.login" finished-at="2020-10-29T21:08:27Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestCase04_getReadArticleScore.enterMy()[pri:0, instance:first.TestCase04_getReadArticleScore@52feb982] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestCase04_getReadArticleScore.enterMy()[pri:0, instance:first.TestCase04_getReadArticleScore@52feb982] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at first.Runtest.main(Runtest.java:16)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterMy -->
        <test-method status="SKIP" signature="readArticle()[pri:0, instance:first.TestCase04_getReadArticleScore@52feb982]" name="readArticle" duration-ms="0" started-at="2020-10-29T21:08:27Z" depends-on-methods="first.TestCase04_getReadArticleScore.login" finished-at="2020-10-29T21:08:27Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestCase04_getReadArticleScore.readArticle()[pri:0, instance:first.TestCase04_getReadArticleScore@52feb982] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestCase04_getReadArticleScore.readArticle()[pri:0, instance:first.TestCase04_getReadArticleScore@52feb982] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at first.Runtest.main(Runtest.java:16)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readArticle -->
      </class> <!-- first.TestCase04_getReadArticleScore -->
    </test> <!-- TestCase04 -->
    <test name="TestCase11" duration-ms="1" started-at="2020-10-29T13:08:32Z" finished-at="2020-10-29T13:08:32Z">
      <class name="first.TestCase11_watchVideo">
        <test-method status="FAIL" signature="SetUp()[pri:0, instance:first.TestCase11_watchVideo@32d2fa64]" name="SetUp" is-config="true" duration-ms="21" started-at="2020-10-29T21:08:27Z" finished-at="2020-10-29T21:08:27Z">
          <exception class="io.appium.java_client.service.local.InvalidServerInstanceException">
            <message>
              <![CDATA[Invalid server instance exception has occured: The invalid appium node /Applications/Appium.app/Contents/Resources/app/node_modules/appium/build/lib/main.js has been defined]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.InvalidServerInstanceException: Invalid server instance exception has occured: The invalid appium node /Applications/Appium.app/Contents/Resources/app/node_modules/appium/build/lib/main.js has been definedat io.appium.java_client.service.local.AppiumServiceBuilder.validateNodeStructure(AppiumServiceBuilder.java:107)at io.appium.java_client.service.local.AppiumServiceBuilder.checkAppiumJS(AppiumServiceBuilder.java:290)at io.appium.java_client.service.local.AppiumServiceBuilder.createArgs(AppiumServiceBuilder.java:386)at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:299)at io.appium.java_client.service.local.AppiumDriverLocalService.buildService(AppiumDriverLocalService.java:74)at first.Basic.SetUp(Basic.java:34)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at first.Runtest.main(Runtest.java:16)Caused by: java.io.IOException: The node /Applications/Appium.app/Contents/Resources/app/node_modules/appium/build/lib/main.jsdoesn't existat io.appium.java_client.service.local.AppiumServiceBuilder.validateNodeStructure(AppiumServiceBuilder.java:109)... 23 more]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.InvalidServerInstanceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="SKIP" signature="login()[pri:0, instance:first.TestCase11_watchVideo@32d2fa64]" name="login" duration-ms="0" started-at="2020-10-29T21:08:32Z" finished-at="2020-10-29T21:08:32Z">
          <exception class="io.appium.java_client.service.local.InvalidServerInstanceException">
            <message>
              <![CDATA[Invalid server instance exception has occured: The invalid appium node /Applications/Appium.app/Contents/Resources/app/node_modules/appium/build/lib/main.js has been defined]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.appium.java_client.service.local.InvalidServerInstanceException: Invalid server instance exception has occured: The invalid appium node /Applications/Appium.app/Contents/Resources/app/node_modules/appium/build/lib/main.js has been definedat io.appium.java_client.service.local.AppiumServiceBuilder.validateNodeStructure(AppiumServiceBuilder.java:107)at io.appium.java_client.service.local.AppiumServiceBuilder.checkAppiumJS(AppiumServiceBuilder.java:290)at io.appium.java_client.service.local.AppiumServiceBuilder.createArgs(AppiumServiceBuilder.java:386)at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:299)at io.appium.java_client.service.local.AppiumDriverLocalService.buildService(AppiumDriverLocalService.java:74)at first.Basic.SetUp(Basic.java:34)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at first.Runtest.main(Runtest.java:16)Caused by: java.io.IOException: The node /Applications/Appium.app/Contents/Resources/app/node_modules/appium/build/lib/main.jsdoesn't existat io.appium.java_client.service.local.AppiumServiceBuilder.validateNodeStructure(AppiumServiceBuilder.java:109)... 23 more]]>
            </full-stacktrace>
          </exception> <!-- io.appium.java_client.service.local.InvalidServerInstanceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="SKIP" signature="enterTheSpecificVideo()[pri:0, instance:first.TestCase11_watchVideo@32d2fa64]" name="enterTheSpecificVideo" duration-ms="0" started-at="2020-10-29T21:08:32Z" description="enterVideo" depends-on-methods="first.TestCase11_watchVideo.enterVideo" finished-at="2020-10-29T21:08:32Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestCase11_watchVideo.enterTheSpecificVideo()[pri:0, instance:first.TestCase11_watchVideo@32d2fa64] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestCase11_watchVideo.enterTheSpecificVideo()[pri:0, instance:first.TestCase11_watchVideo@32d2fa64] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at first.Runtest.main(Runtest.java:16)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterTheSpecificVideo -->
        <test-method status="SKIP" signature="enterVideo()[pri:0, instance:first.TestCase11_watchVideo@32d2fa64]" name="enterVideo" duration-ms="0" started-at="2020-10-29T21:08:32Z" description="enterVideo" depends-on-methods="first.TestCase11_watchVideo.login" finished-at="2020-10-29T21:08:32Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestCase11_watchVideo.enterVideo()[pri:0, instance:first.TestCase11_watchVideo@32d2fa64] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestCase11_watchVideo.enterVideo()[pri:0, instance:first.TestCase11_watchVideo@32d2fa64] depends on not successfully finished methodsat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at first.Runtest.main(Runtest.java:16)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterVideo -->
        <test-method status="SKIP" signature="SetOff()[pri:0, instance:first.TestCase11_watchVideo@32d2fa64]" name="SetOff" is-config="true" duration-ms="0" started-at="2020-10-29T21:08:37Z" finished-at="2020-10-29T21:08:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetOff -->
      </class> <!-- first.TestCase11_watchVideo -->
    </test> <!-- TestCase11 -->
  </suite> <!-- Suite -->
</testng-results>
